name: Run Liatrio Tests and Deploy to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
# Build and Run the Container w/ Docker 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag liatrio-exercise:latest

    - name: Start the Container
      run: docker run -d -p 80:80 --name app liatrio-exercise:latest

# Runs tests provided by Liatrio
    - name: run tests
    # Uses version of apprentice-action that does not include unfinished minified JSON test
      uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91
  
# Publish Image to Docker hub
  docker-hub:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
  
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: madisonewebb28/liatrio_exercise_docker
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}